resources:
  - name: metrics-adapter
    type: git
    source:
      uri: git+ssh://git@github.com/SHyx0rmZ/go-metrics-adapter
      private_key: ((deploy-key-metrics-adapter))

  - name: build-status
    type: github-status
    source:
      access_token: ((github-access-token))
      context: Concourse
      repository: SHyx0rmZ/go-metrics-adapter
    check_every: 15m


resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master


jobs:
  - name: go-tests
    plan:
      - get: metrics-adapter
        trigger: true
        version: every
      - put: build-status
        params:
          commit: metrics-adapter
          state: pending
          target_url: https://github.com/SHyx0rmZ/go-metrics-adapter
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: alpine
          inputs:
            - name: metrics-adapter
          run:
            dir: metrics-adapter
            path: /bin/sh
            args:
              - -ec
              - |
                apk update --quiet
                apk add --no-progress build-base git
                go test ./...
        on_failure:
          put: build-status
          params:
            commit: metrics-adapter
            state: failure
            target_url: https://github.com/SHyx0rmZ/go-metrics-adapter
        on_success:
          put: build-status
          params:
            commit: metrics-adapter
            state: success
            target_url: https://github.com/SHyx0rmZ/go-metrics-adapter
